### ISSUE TITLE
Pasting text into the hex view of any array tag's edit dialog enters those hex values as plain text rather than hex values.

### ISSUE THREAD

**Issue by ConstaChugga** [tryashtar/nbt-studio#13]
example: I copy 5 bytes from say.. HxD, being `43 52 41 46 54` (CRAFT). 
If I open the edit dialog for a byte array tag currently and paste into the hex view, it will just paste in `43 52 41 46 54` as if it were plain text. This is annoying.
What it *should* do is actually be pasting the numbers those hex values represent into the tag, or if the text contains characters that aren't whitespace or 0-9 a-f A-F, it should yell at you that its not valid hex data.

I'm considering this a bug but it could also count as a feature request? Unsure.

**Comment by tryashtar** [comment]
Hm, I guess it depends on how those programs are writing to the clipboard. If it's really just plain text, then there's nothing better to do than guess how to interpret it, with interpretations like literal 0-f, decimal to hex, or ASCII to bytes all being simultaneously valid and indistinguishable, but giving completely different results.

In that case, I'm most comfortable just pasting in the input exactly as received, since otherwise it would get very opaque. But I'll have to investigate how the clipboard looks incoming from HxD, if there's something that indicates these are bytes, then definitely I'll convert them over

**Comment by tryashtar** [comment]
Actually, maybe I'm misunderstanding you. `43 52 41 46 54` actually already is hex for CRAFT, right? So I'm curious what you would prefer to see appear in the box after pasting

**Comment by ConstaChugga** [comment]
If I paste text that is a bunch of hex values I expect the actual values that text is supposed to represent to be inserted rather than the literal text. So if I paste `FF 10` I'm really pasting decimal `255 16`, not decimal `70 70 32 49 48`.

Functional example: Say I want a list of colours in a byte array tag, maybe pure red, green and bleu (`FF0000`, `00FF00`, and `0000FF`). Currently if I were to try and paste `FF 00 00 00 FF 00 00 00 FF` into the byte array hex editor, what would *actually* be pasted is `46 46 20 30 30 20 30 30 20 30 30 20 46 46 20 30 30 20 30 30 20 30 30 20 46 46`, as that's the literal text representation of `FF 00 00 00 FF 00 00 00 FF`. Which is very clearly not my colours.

Honestly I find it a little odd either of the dialog screens (value and hex view) paste the literal text values rather than the text as values at all, especially since you can *type* the hex values in manually, but not paste them in.

**Comment by tryashtar** [comment]
Oh wow, yeah that's horrible. Okay I'm definitely going to fix this ha

**Comment by tryashtar** [comment]
All done. I had to rewrite the HexBox hex parser, and adjust the paste handler to use that instead of the terrible ASCII conversion.
Old formula required you to paste hex separated by spaces, and any invalid data prevented the paste altogether.
New formula reads character by character. Whitespace terminates the byte, and reading any additional character that prevents parsing uses the previously parsed value. (So basically, `FFAA00` gets read as `FF AA 00`, since `FFA` is too big for a byte). And as a side effect of that, non-hex characters are basically just treated as whitespace. Not sure if that's ideal but it seems to work nicely for most cases.
