### ISSUE TITLE
Cannot copy double tags (or tags containing them), possibly related to regional settings

### ISSUE THREAD

**Issue by NeunEinser** [tryashtar/nbt-studio#15]
This might be related to regional settings. My system's regional settings use comma (,) as decimal separator, and NBTStudio does display double tags like that. Going into edit mode, the value is pre-filled with the value using a comma, rather than a point, which is also invalid.

Note that it would be absolutely fine to just always display a point, and don't care about regional settings. Programming and file formats and variables are always English.

**Comment by tryashtar** [comment]
Ah, thanks for mentioning. I thought I caught most of these, but it's hard to notice since my locale is US 😅

**Comment by tryashtar** [comment]
Alright, would you mind giving this test version a try and letting me know if it works?

[NbtStudio.zip](https://github.com/tryashtar/nbt-studio/files/6463138/NbtStudio.zip)

**Comment by NeunEinser** [comment]
Yes, that works!
That was quick, thank you

**Comment by tryashtar** [comment]
Sweet!
I did want to make it work with the comma style, but the only issue is that I use the SNBT writer/parser for display/input in the entire application, and since Minecraft strictly requires a dot, the writer definitely should use one (else it would be incompatible with Minecraft), and the reader probably should as well

**Comment by NeunEinser** [comment]
As someone who uses a comma in their native language, I find it odd when programs that are otherwise English use a comma, so it's fine ;)
