### ISSUE TITLE
[Missing Feature] Global Chunk Coordinate

### ISSUE THREAD

**Issue by barraIhsan** [tryashtar/nbt-studio#4]
![image](https://user-images.githubusercontent.com/57800056/99681792-24358f80-2ab1-11eb-8a0d-c8aebe9af39a.png)
So we know what chunk we edit it
It's little bit confusing if you want to edit the region file

**Comment by tryashtar** [comment]
I also made it show the block coordinates on hover
![image](https://user-images.githubusercontent.com/26075577/99727347-0d714780-2a75-11eb-9d17-6af3beace283.png)

**Comment by ch-yx** [comment]
> 
> 
> I also made it show the block coordinates on hover
> ![image](https://user-images.githubusercontent.com/26075577/99727347-0d714780-2a75-11eb-9d17-6af3beace283.png)

there is a bug in this picture.
Only chunk 0,0 is read and shows that there are 2 entries inside before you click it.
which could lead some inconsistency.

**Comment by tryashtar** [comment]
Most of the chunks are loaded on demand to make the program more responsive. Any action you take that should access the children (e.g. search) will load it automatically. The first chunk is loaded immediately because the region file format is very loose, and we can check to make sure it's an actual region file instead of an unrelated file type by attempting to load the first chunk
