### ISSUE TITLE
Suggestion: Tabs

### ISSUE THREAD

**Issue by thebigsmileXD** [tryashtar/nbt-studio#6]
It would be quite neat to open multiple files in 1 window using tabs
Alternatively there should be a setting to toggle between opening in tabs and separate windows

**Comment by tryashtar** [comment]
Hmm... I do think I prefer how it works now where you can just open multiple root files in the same tree. Tabs wouldn't be out of the question, but I'd have to do some heavy reevaluating of things, especially undo history, save buttons, and the search window.
Is there a reason you'd want files separated in other tabs instead of next to each other in the same view?

**Comment by thebigsmileXD** [comment]
I actually forgot about the tree being able to show multiple files. I guess this idea is kind of unnecessary in that case, because
> next to each other

actually sounds more practical
