### ISSUE TITLE
will this project be updated?

### ISSUE THREAD

**Issue by thewanderingtraderm** [tryashtar/nbt-studio#67]

**Comment by tryashtar** [comment]
What kinds of updates are you interested in?

**Comment by Hippie459MN** [comment]
Not sure what kind of updates are you looking for. I'm not having any issues with the current version here.

**Comment by thewanderingtraderm** [comment]
Idk, it's just that it hasn't been updated in 2 yrs

**Comment by thewanderingtraderm** [comment]
Maybe support for new nbt stuff added in 1.20.5

**Comment by tryashtar** [comment]
I'm not aware of any changes to the NBT format in 1.20.5. If you're referring to item components, those are still saved as NBT and can be edited just as before.

**Comment by thewanderingtraderm** [comment]
you're welcome to not update this program if you want to

**Comment by thewanderingtraderm** [comment]
ok i decided, i want this program to be as good as universal minecraft tool. unfortunately the dev became greedy and made the software paid, and no other software comes close to universal minecraft tool

**Comment by thewanderingtraderm** [comment]
![Screenshot 2024-08-26 210007](https://github.com/user-attachments/assets/42eb3e5c-6735-4bbb-b34c-744ab423b303)

@tryashtar why?

**Comment by tryashtar** [comment]
There's a few reasons. I'm not satisfied with the codebase. The undo system and tree view update model are cumbersome and make it very difficult to implement the features I want. And it's been sufficiently long since working on it that I would have to re-familiarize myself, which I don't care to do. I no longer use Windows as my daily system, which makes me less willing to work further on a program that uses Windows technologies. Meanwhile, I have been unable to find an alternative cross-platform GUI framework that I am satisfied with. The program continues to work sufficiently for my needs, so everything else is just a nice-to-have. I am not very good at time management, and cannot dedicate time to working on this, when I have other projects I consider more important that I'm already not getting done quickly enough.
